// Self-hosts the web fonts: fetches Google Fonts' woff2 files (latin + cyrillic
// subsets) and writes a local @font-face stylesheet, so the site makes no request
// to Google (faster first paint, no third-party IP leak / GDPR concern).
// Run: `node scripts/gen-fonts.mjs`. Arimo is intentionally dropped — the sans
// stack falls back to system Helvetica/Arial, which is metric-identical.
import { mkdirSync, writeFileSync } from 'fs';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Unbounded:wght@600;700&family=JetBrains+Mono:wght@400;500;600;700&display=swap';
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const KEEP = new Set(['latin', 'cyrillic', 'cyrillic-ext']);

const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
const css = await res.text();

const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
mkdirSync('public/fonts', { recursive: true });

let out = '/* Self-hosted fonts — generated by scripts/gen-fonts.mjs. Do not edit. */\n\n';
const files = [];
let m;
while ((m = blockRe.exec(css))) {
  const subset = m[1];
  if (!KEEP.has(subset)) continue;
  let block = m[2];
  const fam = (block.match(/font-family:\s*['"]([^'"]+)['"]/) || [])[1];
  const wght = (block.match(/font-weight:\s*(\d+)/) || [])[1];
  const url = (block.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
  if (!fam || !wght || !url) continue;
  const slug = fam.toLowerCase().replace(/\s+/g, '-');
  const fname = `${slug}-${wght}-${subset}.woff2`;
  files.push({ url, fname });
  block = block.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url("/fonts/${fname}")`);
  out += `/* ${fam} ${wght} ${subset} */\n${block}\n\n`;
}

for (const f of files) {
  const buf = Buffer.from(await (await fetch(f.url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  writeFileSync(`public/fonts/${f.fname}`, buf);
  console.log('font', f.fname, buf.length, 'bytes');
}

writeFileSync('src/styles/fonts.css', out);
console.log('\nwrote src/styles/fonts.css with', files.length, 'faces');
